version: "3.9"

services:
  web:
    build: .
    container_name: web_dev_web
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    volumes:
      - .:/app
    restart: unless-stopped

  pg:
    image: postgres
    environment:
      POSTGRES_DB: web_database
      POSTGRES_USER: web_user
      POSTGRES_PASSWORD: web_password
    ports:
      - "5432:5432"